.\" groff -man -Tascii foo.1
.\"
.TH GNOME Internet Radio Locator 1 "FEBRUARY 2018" GNOME "User Manuals"
.SH NAME
gnome-internet-radio-locator \- GNOME Internet Radio Locator
.SH SYNOPSIS
.B gnome-internet-radio-locator
.br
.SH DESCRIPTION
.B GNOME Internet Radio Locator
allows users to easily listen to live radio programs on radio broadcasters on the Internet.
.SH MOTIVATION
The motivation behind this program is to support the user with easy access to independent, free Internet radio stations around the world. Enjoy Internet Radio.
.SH PLATFORM
.B GNOME Internet Radio Locator
is developed for the GNOME 3 desktop and requires gstreamer to be installed for
playback for live radio streams of supported radio stations.
.SH USAGE
.IP gnome-internet-radio-locator
.I "\--help"
display help screen
.RS
Default radio station configuration
.SH BUGS
https://gitlab.gnome.org/GNOME/gnome-internet-radio-locator/issues
.SH UPDATES
https://gitlab.gnome.org/GNOME/gnome-internet-radio-locator
.SH AUTHORS
.B 
Ole Aamot <ole@src.gnome.org>
.SH "SEE ALSO"
.BR gstreamer
